### ISSUE TITLE
Unable to load images in 1.0.0rc3

### ISSUE THREAD

**Issue by dteinferno** [JaneliaSciComp/Neuroptikon#61]
I am unable to load images in the Windows version. I am told: 

string indices must be integers, not str (TypeError)
Traceback:
 File "CComplex.py", line 481, in <module>
 File "network\network.pyc", line 285, in createNeuron
 File "network\neuron.pyc", line 93, in _init_

**Comment by csweaver** [comment]
I've switched the neuron image parameter to take a dictionary instead of a string so that you can attach a label to an image. This will require that you change your scripts, sorry!

I've updated the wiki to give and example:
https://github.com/JaneliaSciComp/Neuroptikon/wiki/Writing-Scripts-for-Neuroptikon
Or you can check the "Neuron Image Example.py" script.

**Comment by dteinferno** [comment]
The "Neuron Image Example.py" script with the release is still the old one, but I got everything to work with your wiki example. Thanks!
